---

- name: Create systemd/resolved.conf.d directory
  become: true
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    owner: root
    group: root
    mode: "0555"
    state: directory

- name: Configure systemd-resolved
  become: true
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: "/etc/systemd/resolved.conf.d/{{ systemd_resolved.config_file | default('ansible_config.conf') }}"
    owner: root
    group: root
    mode: "0444"
  notify: systemd-resolved.reload
